abbr -a l   "exa"
abbr -a ls  "exa"
abbr -a ll  "exa -l"
abbr -a lll "exa -la"

abbr -a g   "git"
abbr -a gst "git status"
abbr -a gss "git stash save"
abbr -a gsl "git stash list"
abbr -a gl  "git log"
abbr -a gll "git log --oneline --graph --all"
abbr -a gf  "git fetch"
abbr -a gr  "git rebase"
abbr -a gd  "git diff"
abbr -a gds "git diff --staged"
abbr -a ga  "git add"
abbr -a gc  "git commit"
abbr -a gp  "git push"
